name: Send mail after workflow

on:
    workflow_dispatch:

jobs:
    send_mail:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: "Setup Python Environment"
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            
            - name: Install dependencies
              run: python -m pip install --upgrade pip
            - name: Execute python script to send Mail
              run: python main.py
              env:
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                WORKFLOW_RUN_ID: ${{ github.run_id }}
                APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                RECIEVER_EMAIL: ${{ secrets.RECIEVER_EMAIL }}